---
title: "USA State Education Ranking"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
USA_Education_Proportions <- read.csv("C:/Users/josea/OneDrive/WorkSpace/Research/USA_Education_Proportions_updatedforpuerto.csv", header=FALSE)


names(USA_Education_Proportions) <- c("State", "Algebra I", "Geometry", "Algebra II", "Adv. Math I", "Calculus", "Biology", "Chemistry", "Physics", "FTE COUNT", "Meeting all Lic and cert", "First year", "Second year", "SAT-ACT COUNT", "Total Enrollment", "At least one AP COUNT", "SAT-ACT", "AP")

USA_Education_Proportions <- USA_Education_Proportions[-1, ]

```

```{r eval=FALSE, include=FALSE}
#removes the first entry of the data...it cell represents the combined states

#USA_Education_Proportions <- USA_Education_Proportions[-1, ]

```

```{r}
#run chunk in case I need to remove the COUNT columns
USA_Education_Proportions <- USA_Education_Proportions[,-10]
USA_Education_Proportions <- USA_Education_Proportions[,-13]
USA_Education_Proportions <- USA_Education_Proportions[,-13]
USA_Education_Proportions <- USA_Education_Proportions[,-13]

```

```{r}

# Remove the first element from each vector in the list
my_list <- lapply(USA_Education_Proportions, function(x) x[-1])

# Remove the first vector from the list
my_list <- my_list[-1]

# Print the modified list
print(my_list)

```


```{r}
# Convert list to matrix
#all_states <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming")


# Each row represents a feature from the original dataframe. Need to transpose in order to 
my_matrix <- matrix(unlist(my_list), nrow = length(my_list), byrow = FALSE)


print(my_matrix) #matrix is missing wymoming and puerto rico will work on this in pyton to avoid the list fiazco 


```

```{r eval=FALSE, include=FALSE}
#skip this chunk of code for the time being

replace_na_with_mean <- function(x) {
  column_mean <- mean(x, na.rm = TRUE)
  x[is.na(x)] <- column_mean
  return(x)
}

# Apply the function to each column of the matrix
matrix_without_na <- apply(my_matrix, 2, replace_na_with_mean)
```


```{r}
#creating a numeric matrix 
numeric_matrix <- as.numeric(my_matrix)
fin_mat=matrix(numeric_matrix,13,52) 
```

```{r}
a=eigen(fin_mat%*%t(fin_mat))$values #eigen values of covariance matrix of fin_mat

plot(a)

```

```{r}
#viewing covariance matrix of final matrix from previous chunk
#how the information is scaled to understand the principle components in an easier plot axis

w= cov(fin_mat)

b=eigen(w%*%t(w))$values

plot(b)


```
 
```{r}
# covariance final matrix transposed due to viewing the parameters on the x-axis

w = cov(t(fin_mat))

b=eigen(w%*%t(w))$values
```

```{r}
u=eigen(fin_mat%*%t(fin_mat))$vectors

plot(u[,1])

plot(u[,1],u[,2])
```


```{r}
r=eigen(t(fin_mat)%*%fin_mat)$vectors

plot(r[,1])
plot(r[,1],r[,2])

plot(r[,2],r[,3])

plot(r[,1],r[,3])

plot(r[,1],r[,4])


plot(r[,1],r[,2])
```
```{r}
kmeans(r[,1:2],4)

kmeans(r[,1:2],3)


```

```{r}
kmeans(r[,1])

kmeans(r[,1],2)

kmeans(r[,1],3)

kmeans(r[,1],2)

kmeans(r[,1],4)
kmeans(r[,1],3)

kmeans(r[,1:2],3)

kmeans(r[,1:2],4)
```


Goal to use PCA plot with labels

```{r}
pca <- prcomp(t(fin_mat), scale=TRUE) 
 
## plot pc1 and pc2
plot(pca$x[,1], pca$x[,2])
 
## make a scree plot
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
 
barplot(pca.var.per, main="Scree Plot", xlab="Principal Component", ylab="Percent Variation")
```


```{r}
## now make a fancy looking plot that shows the PCs and the variation:
library(ggplot2)
 
pca.data <- data.frame(Sample=rownames(pca$x),
  X=pca$x[,1],
  Y=pca$x[,2])
pca.data
 
ggplot(data=pca.data, aes(x=X, y=Y, label=Sample)) +
  geom_text() +
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) +
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) +
  theme_bw() +
  ggtitle("My PCA Graph")
 
## get the name of the top 10 measurements (genes) that contribute
## most to pc1.
loading_scores <- pca$rotation[,1]
gene_scores <- abs(loading_scores) ## get the magnitudes
gene_score_ranked <- sort(gene_scores, decreasing=TRUE)
top_10_genes <- names(gene_score_ranked[1:10])
 
top_10_genes ## show the names of the top 10 genes
 
pca$rotation[top_10_genes,1] ## show the scores (and +/- sign)
```


